ShortUrlApi: ApiQueryShortUrl Class Reference
ApiQueryShortUrl Class Reference
Query API for ShortUrl page properties.
Public Member Functions
__construct ($query, $moduleName)
For parameters and semantics, see ApiQueryBase::__construct().
execute ()
For parameters and semantics, see ApiQueryBase::execute().
getAllowedParams ()
For parameters and semantics, see ApiQueryBase::getAllowedParams().
getDescription ()
For parameters and semantics, see ApiQueryBase::getDescription().
getExamples ()
For parameters and semantics, see ApiQueryBase::getExamples().
getParamDescription ()
For parameters and semantics, see ApiQueryBase::getParamDescription().
Public Attributes
const MAX_PAGES = 100
Limit the number of pages we’ll query in a single invocation.
const MID = MW_EXT_SHORTURLAPI_API_MID
module ID (short 2- or 3-letter code), without the trailing 'q'
const VERSION = MW_EXT_SHORTURLAPI_VERSION
Our API version.
Private Member Functions
_executeQuery ($params)
Perform our part of the query.
_queryDB ($pageids)
Perform the DB query.
Detailed Description
Query API for ShortUrl page properties.
Definition at line 31 of file ApiQueryShortUrl.php.
Constructor & Destructor Documentation
ApiQueryShortUrl::__construct ($query, $moduleName)
For parameters and semantics, see ApiQueryBase::__construct().
Definition at line 46 of file ApiQueryShortUrl.php.
Member Function Documentation
ApiQueryShortUrl::_executeQuery ($params) private
Perform our part of the query.
Parameters
[in] array $params array of parameters (e.g. from ApiBase::extractRequestParams)
Returns
array
Definition at line 102 of file ApiQueryShortUrl.php.
References _queryDB(), ApiShortUrl\codeFromId(), and ApiShortUrl\getPathTemplate().
Referenced by execute().
ApiQueryShortUrl::_queryDB ($pageids) private
Perform the DB query.
Definition at line 166 of file ApiQueryShortUrl.php.
Referenced by _executeQuery().
ApiQueryShortUrl::execute ()
For parameters and semantics, see ApiQueryBase::execute().
Definition at line 51 of file ApiQueryShortUrl.php.
References _executeQuery().
ApiQueryShortUrl::getAllowedParams ()
For parameters and semantics, see ApiQueryBase::getAllowedParams().
Definition at line 57 of file ApiQueryShortUrl.php.
ApiQueryShortUrl::getDescription ()
For parameters and semantics, see ApiQueryBase::getDescription().
Definition at line 79 of file ApiQueryShortUrl.php.
ApiQueryShortUrl::getExamples ()
For parameters and semantics, see ApiQueryBase::getExamples().
Definition at line 84 of file ApiQueryShortUrl.php.
ApiQueryShortUrl::getParamDescription ()
For parameters and semantics, see ApiQueryBase::getParamDescription().
Definition at line 71 of file ApiQueryShortUrl.php.
Member Data Documentation
const ApiQueryShortUrl::MAX_PAGES = 100
Limit the number of pages we’ll query in a single invocation.
We impose this limit because we're doing an outer join, which can become expensive for large sets.
Definition at line 43 of file ApiQueryShortUrl.php.
const ApiQueryShortUrl::MID = MW_EXT_SHORTURLAPI_API_MID
module ID (short 2- or 3-letter code), without the trailing 'q'
Definition at line 37 of file ApiQueryShortUrl.php.
const ApiQueryShortUrl::VERSION = MW_EXT_SHORTURLAPI_VERSION
Our API version.
Definition at line 34 of file ApiQueryShortUrl.php.
The documentation for this class was generated from the following file:
ShortUrlApi/ApiQueryShortUrl.php