ShortUrlApi: ApiShortUrl Class Reference
ApiShortUrl Class Reference
API for the ShortUrl extension.
Public Member Functions
__construct ($query, $moduleName)
For parameters and semantics, see ApiBase::__construct.
execute ()
For parameters and semantics, see ApiBase::execute.
getAllowedParams ()
For parameters and semantics, see ApiBase::getAllowedParams.
getDescription ()
For parameters and semantics, see ApiBase::getDescription.
getExamples ()
For parameters and semantics, see ApiBase::getExamples.
getParamDescription ()
For parameters and semantics, see ApiBase::getParamDescription.
Static Public Member Functions
static codeFromId ($id)
Get a ShortUrl code from its ShortUrl numeric ID.
static getNamespaceText ($index)
Get the namespace text from the namespace id number.
static getPathTemplate ()
create the template for the short URL path
static idFromCode ($code)
Get a ShortUrl numeric ID from its ShortUrl code.
Public Attributes
const MID = MW_EXT_SHORTURLAPI_API_MID
module ID (short 2- or 3-letter code)
const PARAM_CODES = 'codes'
name of 'codes' query parameter (without the MID)
const PARAM_NAME = MW_EXT_SHORTURLAPI_PARAM_NAME
query parameter name
const VERSION = MW_EXT_SHORTURLAPI_VERSION
Our API version.
Private Member Functions
_queryDB ($codes)
Query the ShortUrl database for details about specified ShortUrl codes.
Private Attributes
$_moduleName
the name of our module, as provided to our constructor
Static Private Attributes
static $_allowMissingShortUrlExtensionNotice = true
flag to prevent repeat warnings of missing ShortUrl extension during the same request
static $_needToWarnAboutOrphanURLs = true
flag to prevent repeat warnings of orphan short URLs
Detailed Description
API for the ShortUrl extension.
Definition at line 36 of file ApiShortUrl.php.
Constructor & Destructor Documentation
ApiShortUrl::__construct ($query, $moduleName)
For parameters and semantics, see ApiBase::__construct.
Definition at line 51 of file ApiShortUrl.php.
Member Function Documentation
ApiShortUrl::_queryDB ($codes) private
Query the ShortUrl database for details about specified ShortUrl codes.
Definition at line 224 of file ApiShortUrl.php.
Referenced by execute().
static ApiShortUrl::codeFromId ($id) static
Get a ShortUrl code from its ShortUrl numeric ID.
Parameters
int $id the ShortUrl numeric ID (su_id)
Returns
string that contains the ShortUrl code
Definition at line 207 of file ApiShortUrl.php.
Referenced by ApiQueryShortUrl\_executeQuery(), and execute().
ApiShortUrl::execute ()
For parameters and semantics, see ApiBase::execute.
Definition at line 72 of file ApiShortUrl.php.
References _queryDB(), and codeFromId().
ApiShortUrl::getAllowedParams ()
For parameters and semantics, see ApiBase::getAllowedParams.
Definition at line 123 of file ApiShortUrl.php.
ApiShortUrl::getDescription ()
For parameters and semantics, see ApiBase::getDescription.
Definition at line 142 of file ApiShortUrl.php.
ApiShortUrl::getExamples ()
For parameters and semantics, see ApiBase::getExamples.
Definition at line 151 of file ApiShortUrl.php.
static ApiShortUrl::getNamespaceText ($index) static
Get the namespace text from the namespace id number.
Definition at line 163 of file ApiShortUrl.php.
ApiShortUrl::getParamDescription ()
For parameters and semantics, see ApiBase::getParamDescription.
Definition at line 132 of file ApiShortUrl.php.
static ApiShortUrl::getPathTemplate () static
create the template for the short URL path
Definition at line 187 of file ApiShortUrl.php.
Referenced by ApiQueryShortUrl\_executeQuery().
static ApiShortUrl::idFromCode ($code) static
Get a ShortUrl numeric ID from its ShortUrl code.
Parameters
string $code the ShortUrl code to convert
Returns
int that contains the ShortUrl numeric ID (su_id)
Definition at line 217 of file ApiShortUrl.php.
Member Data Documentation
ApiShortUrl::$_allowMissingShortUrlExtensionNotice = true static private
flag to prevent repeat warnings of missing ShortUrl extension during the same request
Definition at line 260 of file ApiShortUrl.php.
ApiShortUrl::$_moduleName private
the name of our module, as provided to our constructor
Definition at line 257 of file ApiShortUrl.php.
ApiShortUrl::$_needToWarnAboutOrphanURLs = true static private
flag to prevent repeat warnings of orphan short URLs
Definition at line 263 of file ApiShortUrl.php.
const ApiShortUrl::MID = MW_EXT_SHORTURLAPI_API_MID
module ID (short 2- or 3-letter code)
Definition at line 42 of file ApiShortUrl.php.
const ApiShortUrl::PARAM_CODES = 'codes'
name of 'codes' query parameter (without the MID)
Definition at line 48 of file ApiShortUrl.php.
const ApiShortUrl::PARAM_NAME = MW_EXT_SHORTURLAPI_PARAM_NAME
query parameter name
Definition at line 45 of file ApiShortUrl.php.
const ApiShortUrl::VERSION = MW_EXT_SHORTURLAPI_VERSION
Our API version.
Definition at line 39 of file ApiShortUrl.php.
The documentation for this class was generated from the following file:
ShortUrlApi/ApiShortUrl.php