WeirdoCustomDigits: WeirdoCustomDigitsBc Class Reference
WeirdoCustomDigitsBc Class Reference
WeirdoCustomDigits
Implementation of WeirdoCustomDigits using the bc extension for arithmetic.
Public Member Functions
__construct ($digits=null, $radix=null, $use_uc=true)
For parameters and semantics, see WeirdoCustomDigits::__construct().
customFromDecimal ($decimalNumber, $minCustomDigits=1)
For parameters and semantics, see WeirdoCustomDigits::customFromDecimal().
customFromHex ($hexNumber, $minCustomDigits=1)
For parameters and semantics, see WeirdoCustomDigits::customFromHex().
customFromInternal ($internal, $minCustomDigits=1)
For parameters and semantics, see WeirdoCustomDigits::customFromInternal().
customRandomDigits ($nDigits)
For parameters and semantics, see WeirdoCustomDigits::customRandomDigits().
customRandomFromInternalRange ($rangeInternal)
For parameters and semantics, see WeirdoCustomDigits::customRandomFromInternalRange().
decimalFromCustom ($customNumber)
For parameters and semantics, see WeirdoCustomDigits::decimalFromCustom().
decimalFromInternal ($internal)
For parameters and semantics, see WeirdoCustomDigits::decimalFromInternal().
hexFromCustom ($customNumber)
For parameters and semantics, see WeirdoCustomDigits::hexFromCustom().
hexFromInternal ($internal)
For parameters and semantics, see WeirdoCustomDigits::hexFromInternal().
internalFromCustom ($customNumber)
For parameters and semantics, see WeirdoCustomDigits::internalFromCustom().
internalFromDecimal ($decimalNumber)
For parameters and semantics, see WeirdoCustomDigits::internalFromDecimal().
internalFromHex ($hexNumber)
For parameters and semantics, see WeirdoCustomDigits::internalFromHex().
Public Member Functions inherited from WeirdoCustomDigits
__construct ($digits=null, $radix=null, $use_uc=true)
Class constructor.
customFromDecimal ($decimalNumber, $minCustomDigits=1)
Convert a decimal number to a custom-number string.
customFromHex ($hexNumber, $minCustomDigits=1)
Convert a hexadecimal number to a custom-number string.
customFromInternal ($internal, $minCustomDigits=1)
Convert an internally represented number to a custom-number string.
customRandomDigits ($nDigits)
Get a specified number of random custom-number digits.
customRandomFromInternalRange ($rangeInternal)
Get a random custom number within specified range.
decimalFromCustom ($customNumber)
Convert a binary-number string to a decimal-number string.
decimalFromInternal ($internal)
Convert an internally represented number to a decimal-number string.
hexFromCustom ($customNumber)
Convert a custom-number string to a hexadecimal string.
hexFromInternal ($internal)
Convert an internally represented number to a hexadecimal string.
hexFromRandomBits ($nBits)
Get random bits, represented as a hexadecimal string.
init ($digits=null, $radix=null, $use_uc=true)
Class instance initializer.
internalFromCustom ($customNumber)
Convert a custom-number string to an internally represented (opaque) number.
internalFromDecimal ($decimalNumber)
Convert a decimal-number string to an internally represented (opaque) number.
internalFromHex ($hexNumber)
Convert a hexadecimal string to an internally represented (opaque) number.
validateCustomDigit ($customNumberDigit)
Validate a single digit of a custom number.
validateCustomNumber ($customNumber)
Validate a custom-number string.
Static Public Member Functions
static _initStatic ()
For semantics, see WeirdoCustomDigits::_initStatic().
static binFromDecimal ($decimalNumber)
For parameters and semantics, see WeirdoCustomDigits::binFromDecimal().
static decimalFromBin ($binNumber)
For parameters and semantics, see WeirdoCustomDigits::decimalFromBin().
static decimalFromHex ($hexNumber)
For parameters and semantics, see WeirdoCustomDigits::decimalFromHex().
static hexFromDecimal ($decimalNumber)
For parameters and semantics, see WeirdoCustomDigits::hexFromDecimal().
Static Public Member Functions inherited from WeirdoCustomDigits
static _initStatic ()
Initialize this class's static properties.
static binFromDecimal ($decimalNumber)
Convert a decimal number/string to a binary-number string of zero (0) and one (1) characters.
static binFromHex ($hexNumber)
Convert a hexadecimal string to a binary-number string of zero (0) and one (1) characters.
static decimalFromBin ($binNumber)
Convert a binary-number string to a decimal-number string.
static decimalFromHex ($hexNumber)
static hexFromBin ($binNumber)
Convert a binary-number string to a hexadecimal string.
static hexFromDecimal ($decimalNumber)
Convert a decimal-number string to a hexadecimal string.
static uc_str_split ($str)
Split a unicode string into an array of its individual characters.
Static Public Attributes
static $maximumValue = null
For semantics, see WeirdoCustomDigits::$maximumValue.
Static Public Attributes inherited from WeirdoCustomDigits
static $maximumValue = null
The maximum value of a number.
static $phpIntegerMaxBits = WeirdoCustomDigits::IEEE_754_SIGNIFICAND_BITS
Maximum of contiguous range of integers that PHP supports for arithmetic.
Protected Member Functions
_getBitsNeededForRangeInternal ($rangeInternal)
For parameters and semantics, see WeirdoCustomDigits::_getBitsNeededForRangeInternal().
_getRangeNeededForCustomDigits ($nDigits)
For parameters and semantics, see WeirdoCustomDigits::_getRangeNeededForCustomDigits().
Protected Member Functions inherited from WeirdoCustomDigits
_getBitsNeededForRangeInternal ($rangeInternal)
Get the number of binary bits needed to represent a number less than the specified limit.
_getRangeNeededForCustomDigits ($nDigits)
Get the range of numbers needed for the specified number of custom-number digits.
_trim_array_lru (&$array, $maxCount, $chunkSize)
Trim an array, removing least-recently added elements.
str_split ($str)
Split a string into an array of its individual characters, depending on Unicode property.
Static Protected Attributes
static $_hexChunkPaddingFormat
printf format to left-zero-fill a hex string to the number of hex digits we extract with self::$_dechexDivisor
Static Protected Attributes inherited from WeirdoCustomDigits
static $_binChunkPaddingFormat
printf format to left-zero-fill a binary-digit string to the number of bits that corresponds to self::$_hexbinChunkSize
static $_binhexChunkSize
The number of binary digits that corresponds to self::$_hexbinChunkSize.
static $_hexbinChunkSize
The maximum number of hexadecimal digits that both decbin(hexdec($hex)) and dechex(bindec($binary)) can handle.
static $_hexChunkPaddingFormat
printf format to left-zero-fill a hex string to the number of hex digits specified by self::$_hexbinChunkSize
Static Private Attributes
static $_bindecChunkSize
This int represents the number of bits that corresponds to _hexdecChunkSize.
static $_dechexDivisor
Divisor for extracting digits for decimal-to-hex conversion.
static $_hexdecChunkSize
This int represents the number of whole hexadecimal digits that hexdec() can handle.
Additional Inherited Members
Public Attributes inherited from WeirdoCustomDigits
$allowNonCryptoRandom
Set to true only if openssl random is not crypto safe.
const DIGITS_10_ARABIC_EAST = ''
Arabic decimal digits (UTF-8)
const DIGITS_51_READABLE = 'wkW34679AabCcDdEeFfGgHhiJjKLMmNnoPpQqRrsTtUuVvXxYyz'
Digits up to base 51 less likely to be misread These consists of a subset of the typical base-62 digits, less these eleven digits: 0O 1Ll 2Z 5S 8B.
const DIGITS_62_GMP = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
Digits compatibile with gmp from base 37 to base 62.
const DIGITS_70 = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_.*~!()-'
Digits for radixes up to base 70 (including bc and gmp up to base 36)
const IEEE_754_SIGNIFICAND_BITS = 53
Precision of IEEE 754 floating point number.
const VERSION = '1.0.0'
Class version.
Protected Attributes inherited from WeirdoCustomDigits
$_bitsNeededForRange
Array of number of bits by range of numbers.
$_digitsArray
An array of custom-number digits.
$_digitValues
An associative array that maps custom-number digits to their numerical values.
$_radix
The radix of the custom number.
$_rangeNeededForDigits
Custom number ranges by number of digits.
Detailed Description
Implementation of WeirdoCustomDigits using the bc extension for arithmetic.
Requirements
bc extension (See http://php.net/bc)
Limitations
None more than WeirdoCustomDigits.
The "internally represented" format for values of this subclass is a string of decimal digits.
Definition at line 34 of file WeirdoCustomDigitsBc.php.
Constructor & Destructor Documentation
WeirdoCustomDigitsBc::__construct ($digits = null, $radix = null, $use_uc = true)
For parameters and semantics, see WeirdoCustomDigits::__construct().
This subclass method throws an error if the bc extension is not available.
Definition at line 48 of file WeirdoCustomDigitsBc.php.
Member Function Documentation
WeirdoCustomDigitsBc::_getBitsNeededForRangeInternal ($rangeInternal) protected
For parameters and semantics, see WeirdoCustomDigits::_getBitsNeededForRangeInternal().
Access:
private
Definition at line 257 of file WeirdoCustomDigitsBc.php.
Referenced by customRandomFromInternalRange().
WeirdoCustomDigitsBc::_getRangeNeededForCustomDigits ($nDigits) protected
For parameters and semantics, see WeirdoCustomDigits::_getRangeNeededForCustomDigits().
Access:
private
Definition at line 268 of file WeirdoCustomDigitsBc.php.
Referenced by customRandomDigits().
static WeirdoCustomDigitsBc::_initStatic () static
For semantics, see WeirdoCustomDigits::_initStatic().
Access:
private
Definition at line 279 of file WeirdoCustomDigitsBc.php.
static WeirdoCustomDigitsBc::binFromDecimal ($decimalNumber) static
For parameters and semantics, see WeirdoCustomDigits::binFromDecimal().
Definition at line 59 of file WeirdoCustomDigitsBc.php.
WeirdoCustomDigitsBc::customFromDecimal ($decimalNumber, $minCustomDigits = 1)
For parameters and semantics, see WeirdoCustomDigits::customFromDecimal().
Definition at line 75 of file WeirdoCustomDigitsBc.php.
References customFromInternal().
WeirdoCustomDigitsBc::customFromHex ($hexNumber, $minCustomDigits = 1)
For parameters and semantics, see WeirdoCustomDigits::customFromHex().
Definition at line 81 of file WeirdoCustomDigitsBc.php.
References customFromInternal().
WeirdoCustomDigitsBc::customFromInternal ($internal, $minCustomDigits = 1)
For parameters and semantics, see WeirdoCustomDigits::customFromInternal().
Definition at line 87 of file WeirdoCustomDigitsBc.php.
Referenced by customFromDecimal(), customFromHex(), and customRandomFromInternalRange().
WeirdoCustomDigitsBc::customRandomDigits ($nDigits)
For parameters and semantics, see WeirdoCustomDigits::customRandomDigits().
Definition at line 101 of file WeirdoCustomDigitsBc.php.
References _getRangeNeededForCustomDigits(), and customRandomFromInternalRange().
WeirdoCustomDigitsBc::customRandomFromInternalRange ($rangeInternal)
For parameters and semantics, see WeirdoCustomDigits::customRandomFromInternalRange().
Definition at line 109 of file WeirdoCustomDigitsBc.php.
References _getBitsNeededForRangeInternal(), customFromInternal(), and WeirdoCustomDigits\hexFromRandomBits().
Referenced by customRandomDigits().
static WeirdoCustomDigitsBc::decimalFromBin ($binNumber) static
For parameters and semantics, see WeirdoCustomDigits::decimalFromBin().
Definition at line 129 of file WeirdoCustomDigitsBc.php.
References WeirdoCustomDigits\str_split().
WeirdoCustomDigitsBc::decimalFromCustom ($customNumber)
For parameters and semantics, see WeirdoCustomDigits::decimalFromCustom().
Definition at line 187 of file WeirdoCustomDigitsBc.php.
References internalFromCustom().
static WeirdoCustomDigitsBc::decimalFromHex ($hexNumber) static
For parameters and semantics, see WeirdoCustomDigits::decimalFromHex().
Definition at line 158 of file WeirdoCustomDigitsBc.php.
References WeirdoCustomDigits\str_split().
WeirdoCustomDigitsBc::decimalFromInternal ($internal)
For parameters and semantics, see WeirdoCustomDigits::decimalFromInternal().
Definition at line 193 of file WeirdoCustomDigitsBc.php.
WeirdoCustomDigitsBc::hexFromCustom ($customNumber)
For parameters and semantics, see WeirdoCustomDigits::hexFromCustom().
Definition at line 215 of file WeirdoCustomDigitsBc.php.
References internalFromCustom().
static WeirdoCustomDigitsBc::hexFromDecimal ($decimalNumber) static
For parameters and semantics, see WeirdoCustomDigits::hexFromDecimal().
Definition at line 199 of file WeirdoCustomDigitsBc.php.
WeirdoCustomDigitsBc::hexFromInternal ($internal)
For parameters and semantics, see WeirdoCustomDigits::hexFromInternal().
Definition at line 220 of file WeirdoCustomDigitsBc.php.
WeirdoCustomDigitsBc::internalFromCustom ($customNumber)
For parameters and semantics, see WeirdoCustomDigits::internalFromCustom().
Definition at line 225 of file WeirdoCustomDigitsBc.php.
References WeirdoCustomDigits\str_split().
Referenced by decimalFromCustom(), and hexFromCustom().
WeirdoCustomDigitsBc::internalFromDecimal ($decimalNumber)
For parameters and semantics, see WeirdoCustomDigits::internalFromDecimal().
Definition at line 244 of file WeirdoCustomDigitsBc.php.
WeirdoCustomDigitsBc::internalFromHex ($hexNumber)
For parameters and semantics, see WeirdoCustomDigits::internalFromHex().
Definition at line 250 of file WeirdoCustomDigitsBc.php.
Member Data Documentation
WeirdoCustomDigitsBc::$_bindecChunkSize static private
This int represents the number of bits that corresponds to _hexdecChunkSize.
Definition at line 298 of file WeirdoCustomDigitsBc.php.
WeirdoCustomDigitsBc::$_dechexDivisor static private
Divisor for extracting digits for decimal-to-hex conversion.
Definition at line 292 of file WeirdoCustomDigitsBc.php.
WeirdoCustomDigitsBc::$_hexChunkPaddingFormat static protected
printf format to left-zero-fill a hex string to the number of hex digits we extract with self::$_dechexDivisor
Definition at line 304 of file WeirdoCustomDigitsBc.php.
WeirdoCustomDigitsBc::$_hexdecChunkSize static private
This int represents the number of whole hexadecimal digits that hexdec() can handle.
Definition at line 295 of file WeirdoCustomDigitsBc.php.
WeirdoCustomDigitsBc::$maximumValue = null static
For semantics, see WeirdoCustomDigits::$maximumValue.
For this class, the value is null, indicating that there is no limit.
Definition at line 41 of file WeirdoCustomDigitsBc.php.
The documentation for this class was generated from the following file:
WeirdoCustomDigitsBc.php