WeirdoCustomDigits: WeirdoCustomDigits Class Reference
WeirdoCustomDigits Class Reference
WeirdoCustomDigits
Abstract class for converting custom numbers with arbitrary radixes and digit characters.
Public Member Functions
__construct ($digits=null, $radix=null, $use_uc=true)
Class constructor.
customFromDecimal ($decimalNumber, $minCustomDigits=1)
Convert a decimal number to a custom-number string.
customFromHex ($hexNumber, $minCustomDigits=1)
Convert a hexadecimal number to a custom-number string.
customFromInternal ($internal, $minCustomDigits=1)
Convert an internally represented number to a custom-number string.
customRandomDigits ($nDigits)
Get a specified number of random custom-number digits.
customRandomFromInternalRange ($rangeInternal)
Get a random custom number within specified range.
decimalFromCustom ($customNumber)
Convert a binary-number string to a decimal-number string.
decimalFromInternal ($internal)
Convert an internally represented number to a decimal-number string.
hexFromCustom ($customNumber)
Convert a custom-number string to a hexadecimal string.
hexFromInternal ($internal)
Convert an internally represented number to a hexadecimal string.
hexFromRandomBits ($nBits)
Get random bits, represented as a hexadecimal string.
init ($digits=null, $radix=null, $use_uc=true)
Class instance initializer.
internalFromCustom ($customNumber)
Convert a custom-number string to an internally represented (opaque) number.
internalFromDecimal ($decimalNumber)
Convert a decimal-number string to an internally represented (opaque) number.
internalFromHex ($hexNumber)
Convert a hexadecimal string to an internally represented (opaque) number.
validateCustomDigit ($customNumberDigit)
Validate a single digit of a custom number.
validateCustomNumber ($customNumber)
Validate a custom-number string.
Static Public Member Functions
static _initStatic ()
Initialize this class's static properties.
static binFromDecimal ($decimalNumber)
Convert a decimal number/string to a binary-number string of zero (0) and one (1) characters.
static binFromHex ($hexNumber)
Convert a hexadecimal string to a binary-number string of zero (0) and one (1) characters.
static decimalFromBin ($binNumber)
Convert a binary-number string to a decimal-number string.
static decimalFromHex ($hexNumber)
static hexFromBin ($binNumber)
Convert a binary-number string to a hexadecimal string.
static hexFromDecimal ($decimalNumber)
Convert a decimal-number string to a hexadecimal string.
static uc_str_split ($str)
Split a unicode string into an array of its individual characters.
Public Attributes
$allowNonCryptoRandom
Set to true only if openssl random is not crypto safe.
const DIGITS_10_ARABIC_EAST = '٠١٢٣٤٥٦٧٨٩'
Arabic decimal digits (UTF-8)
const DIGITS_51_READABLE = 'wkW34679AabCcDdEeFfGgHhiJjKLMmNnoPpQqRrsTtUuVvXxYyz'
Digits up to base 51 less likely to be misread These consists of a subset of the typical base-62 digits, less these eleven digits: 0O 1Ll 2Z 5S 8B.
const DIGITS_62_GMP = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
Digits compatibile with gmp from base 37 to base 62.
const DIGITS_70 = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_.*~!()-'
Digits for radixes up to base 70 (including bc and gmp up to base 36)
const IEEE_754_SIGNIFICAND_BITS = 53
Precision of IEEE 754 floating point number.
const VERSION = '1.0.0'
Class version.
Static Public Attributes
static $maximumValue = null
The maximum value of a number.
static $phpIntegerMaxBits = WeirdoCustomDigits::IEEE_754_SIGNIFICAND_BITS
Maximum of contiguous range of integers that PHP supports for arithmetic.
Protected Member Functions
_getBitsNeededForRangeInternal ($rangeInternal)
Get the number of binary bits needed to represent a number less than the specified limit.
_getRangeNeededForCustomDigits ($nDigits)
Get the range of numbers needed for the specified number of custom-number digits.
_trim_array_lru (&$array, $maxCount, $chunkSize)
Trim an array, removing least-recently added elements.
str_split ($str)
Split a string into an array of its individual characters, depending on Unicode property.
Protected Attributes
$_bitsNeededForRange
Array of number of bits by range of numbers.
$_digitsArray
An array of custom-number digits.
$_digitValues
An associative array that maps custom-number digits to their numerical values.
$_radix
The radix of the custom number.
$_rangeNeededForDigits
Custom number ranges by number of digits.
Static Protected Attributes
static $_binChunkPaddingFormat
printf format to left-zero-fill a binary-digit string to the number of bits that corresponds to self::$_hexbinChunkSize
static $_binhexChunkSize
The number of binary digits that corresponds to self::$_hexbinChunkSize.
static $_hexbinChunkSize
The maximum number of hexadecimal digits that both decbin(hexdec($hex)) and dechex(bindec($binary)) can handle.
static $_hexChunkPaddingFormat
printf format to left-zero-fill a hex string to the number of hex digits specified by self::$_hexbinChunkSize
Private Attributes
$_fn
Function vector for mapable class functions.
$_is_using_uc
Boolean indicator if Unicode is supported by this instance (See initialization parameter $use_uc.)
Detailed Description
Abstract class for converting custom numbers with arbitrary radixes and digit characters.
Requirements
PHP 5.3 or later
If using multi-byte or UTF-8 digits, PCRE UTF-8 support is required.
Limitations
Only non-negative integers ("whole numbers") are supported.
Definition at line 47 of file WeirdoCustomDigits.php.
Constructor & Destructor Documentation
WeirdoCustomDigits::__construct ($digits = null, $radix = null, $use_uc = true)
Class constructor.
Parameters
[in] string | array $digits set of case-sensitive-distinct characters that form the digits of a custom number. The first digit is zero, &c. If an array is passed, each element represents a single digit. (Numbers with multi-CHARACTER digits can be rendered, but not parsed, although multi-BYTE Unicode characters are just fine). Default is WeirdoCustomDigits::DIGITS_70.
[in] int $radix number of digits (i.e. the radix). Default is the number of digits provided in $digits.
[in] bool $use_uc true if to allow Unicode characters in the custom number's set of digits, else allow ASCII only. Default is true.
Example:
// Manipulate base-65 numbers that have the digits [0-9a-zA-Z_.*].
$wrdx = new WeirdoCustomDigitInt(WeirdoCustomDigits::DIGITS_70,65);
Definition at line 105 of file WeirdoCustomDigits.php.
References init().
Member Function Documentation
WeirdoCustomDigits::_getBitsNeededForRangeInternal ($rangeInternal) abstract protected
Get the number of binary bits needed to represent a number less than the specified limit.
Parameters
[in] any $rangeInternal internally represented value of the range limit
Returns
integer number of bits needed to represent numbers in the entire range
WeirdoCustomDigits::_getRangeNeededForCustomDigits ($nDigits) abstract protected
Get the range of numbers needed for the specified number of custom-number digits.
This function returns the limit of the range of numbers that can be expressed by the specified number of digits of the custom number's radix. Numbers can be from zero to this limit.
Parameters
[in] int $nDigits number of custom-number digits
Returns
internally represented limit value
static WeirdoCustomDigits::_initStatic () static
Initialize this class's static properties.
Access:
private
PHP only allows variable declarations with simple constants, so we have this function for more complex initialization of statics. Although "public" in construction, it is usable in this source file, only, immediately after this class is declared. Any attempt to invoke this method a second time will throw an ErrorException.
Definition at line 556 of file WeirdoCustomDigits.php.
WeirdoCustomDigits::_trim_array_lru (& $array, $maxCount, $chunkSize) protected
Trim an array, removing least-recently added elements.
The specified array is always appended to, so we simply remove a "chunk" of elements from the beginning when the array exceeeds the specified maximum.
Parameters
[in,out] array $array the array to trim (if needed)
[in] int $maxCount the maximum number of elements allowed in the array
[in] int $chunkSize the number of elements in a "chunk"
Definition at line 533 of file WeirdoCustomDigits.php.
static WeirdoCustomDigits::binFromDecimal ($decimalNumber) static
Convert a decimal number/string to a binary-number string of zero (0) and one (1) characters.
Access:
abstract
Parameters
[in] string $decimalNumber string of decimal digits (0-9)
Returns
binary-number string of zero (0) and one (1) characters.
Definition at line 231 of file WeirdoCustomDigits.php.
static WeirdoCustomDigits::binFromHex ($hexNumber) static
Convert a hexadecimal string to a binary-number string of zero (0) and one (1) characters.
This method imposes no limit on the number of digits in the given number or in the resulting binary number.
Parameters
[in] string $hexNumber string of hexadecimal digits [0-9a-fA-F]
Returns
binary-number string of zero (0) and one (1) characters.
Definition at line 246 of file WeirdoCustomDigits.php.
References str_split().
WeirdoCustomDigits::customFromDecimal ($decimalNumber, $minCustomDigits = 1) abstract
Convert a decimal number to a custom-number string.
Parameters
[in] int | string $decimalNumber integer or string of decimal digits [0-9]. e.g. '139874'
[in] int $minCustomDigits zero-fill the result to this many digits. Default is 1. (Note that a zero isn't necessarily the ASCII character '0'!)
Returns
custom-number string of custom digit characters
WeirdoCustomDigits::customFromHex ($hexNumber, $minCustomDigits = 1) abstract
Convert a hexadecimal number to a custom-number string.
Parameters
[in] string $hexNumber string of hexadecimal digits [0-9a-fA-F]. Example: 'F3E8'
[in] int $minCustomDigits zero-fill the result to this many digits. Default is 1. (Note that a zero isn't necessarily the ASCII character '0'!)
Returns
custom-number string of custom digit characters
WeirdoCustomDigits::customFromInternal ($internal, $minCustomDigits = 1) abstract
Convert an internally represented number to a custom-number string.
Parameters
[in] any $internal a value returned from another method (e.g. from internalFrom...())
[in] int $minCustomDigits zero-fill the result to this many digits (Note that a zero isn't necessarily the ASCII character '0'!)
Returns
custom-number string of custom digit characters
WeirdoCustomDigits::customRandomDigits ($nDigits) abstract
Get a specified number of random custom-number digits.
Parameters
[in] int $nDigits the number of random digits to obtain
Returns
string of custom-number digits
WeirdoCustomDigits::customRandomFromInternalRange ($rangeInternal) abstract
Get a random custom number within specified range.
Parameters
[in] string $rangeInternal an internally represented (opaque) number, specifying the range of random numbers to obtain (from zero to this number minus one)
Returns
string of custom-number digits
static WeirdoCustomDigits::decimalFromBin ($binNumber) static
Convert a binary-number string to a decimal-number string.
Access:
abstract
Parameters
[in] string $binNumber a binary-number string of zeros and ones
Returns
decimal-number string of decimal digits
Definition at line 312 of file WeirdoCustomDigits.php.
WeirdoCustomDigits::decimalFromCustom ($customNumber) abstract
Convert a binary-number string to a decimal-number string.
Access:
abstract
Parameters
[in] string $customNumber a custom-number string
Returns
decimal-number string of decimal digits
static WeirdoCustomDigits::decimalFromHex ($hexNumber) static
Definition at line 327 of file WeirdoCustomDigits.php.
WeirdoCustomDigits::decimalFromInternal ($internal) abstract
Convert an internally represented number to a decimal-number string.
Parameters
[in] any $internal a value returned from another method (e.g. from internalFrom...())
Returns
decimal-number string of decimal digits
static WeirdoCustomDigits::hexFromBin ($binNumber) static
Convert a binary-number string to a hexadecimal string.
This method imposes no limit on the number of digits in the given number or in the resulting hexadecimal number.
Parameters
[in] string $binNumber a binary-number string of zeros and ones
Returns
hexadecimal string of hexadecimal digits
Definition at line 350 of file WeirdoCustomDigits.php.
References str_split().
WeirdoCustomDigits::hexFromCustom ($customNumber) abstract
Convert a custom-number string to a hexadecimal string.
Parameters
[in] string $customNumber custom-number string
Returns
hexadecimal string
static WeirdoCustomDigits::hexFromDecimal ($decimalNumber) static
Convert a decimal-number string to a hexadecimal string.
Access:
abstract
Parameters
[in] string $decimalNumber decimal-number string
Returns
hexadecimal string
Definition at line 391 of file WeirdoCustomDigits.php.
WeirdoCustomDigits::hexFromInternal ($internal) abstract
Convert an internally represented number to a hexadecimal string.
Parameters
[in] any $internal a value returned from another method (e.g. from internalFrom...())
Returns
hexadecimal string of hexadecimal digits
WeirdoCustomDigits::hexFromRandomBits ($nBits)
Get random bits, represented as a hexadecimal string.
The function returns random bits. Normally, the returned value is crypto-safe, but if the allowNonCryptoRandom property is set, the return value might not be crypto-safe. For additional details, see the PHP library function openssl_random_pseudo_bytes().
Parameters
[in] int $nBits the number of random bits to obtain
Returns
hexadecimal digits.
Definition at line 440 of file WeirdoCustomDigits.php.
Referenced by WeirdoCustomDigitsBc\customRandomFromInternalRange(), WeirdoCustomDigitsGmp\customRandomFromInternalRange(), and WeirdoCustomDigitsInt\customRandomFromInternalRange().
WeirdoCustomDigits::init ($digits = null, $radix = null, $use_uc = true)
Class instance initializer.
This can be called after first-time initialization to change the previous settings (which will be discarded).
Same parameters as __construct().
Definition at line 119 of file WeirdoCustomDigits.php.
References str_split(), and uc_str_split().
Referenced by __construct().
WeirdoCustomDigits::internalFromCustom ($customNumber) abstract
Convert a custom-number string to an internally represented (opaque) number.
Parameters
[in] string $customNumber custom-number string
Returns
internally represented (opaque) number
WeirdoCustomDigits::internalFromDecimal ($decimalNumber) abstract
Convert a decimal-number string to an internally represented (opaque) number.
Parameters
[in] int | string $decimalNumber integer or string of decimal digits [0-9]. e.g. '139874'
Returns
internally represented (opaque) number
WeirdoCustomDigits::internalFromHex ($hexNumber) abstract
Convert a hexadecimal string to an internally represented (opaque) number.
Parameters
[in] string $hexNumber string of hexadecimal digits [0-9a-fA-F]. Example: 'F3E8'
Returns
internally represented (opaque) number
WeirdoCustomDigits::str_split ($str) protected
Split a string into an array of its individual characters, depending on Unicode property.
This function invokes either the PHP library function str_split or this class's method uc_str_split(), depending on if this instance was created or initialized last with the $use_uc flag true or false.
Parameters
[in] string $str string of characters
Returns
array of single-character strings
Definition at line 498 of file WeirdoCustomDigits.php.
Referenced by binFromHex(), WeirdoCustomDigitsBc\decimalFromBin(), WeirdoCustomDigitsBc\decimalFromHex(), hexFromBin(), init(), WeirdoCustomDigitsInt\internalFromCustom(), WeirdoCustomDigitsGmp\internalFromCustom(), WeirdoCustomDigitsBc\internalFromCustom(), and validateCustomNumber().
static WeirdoCustomDigits::uc_str_split ($str) static
Split a unicode string into an array of its individual characters.
(Like the similarly named PHP library function str_split, but with Unicode support.)
Parameters
[in] string $str string of Unicode characters
Returns
array of single-Unicode-character strings
Definition at line 484 of file WeirdoCustomDigits.php.
Referenced by init().
WeirdoCustomDigits::validateCustomDigit ($customNumberDigit)
Validate a single digit of a custom number.
If the validation fails, this method throws an ErrorException error.
Parameters
[in] string $customNumberDigit digit to validate
Definition at line 199 of file WeirdoCustomDigits.php.
Referenced by validateCustomNumber().
WeirdoCustomDigits::validateCustomNumber ($customNumber)
Validate a custom-number string.
Validate each digit in the string
If the validation fails, this method throws an ErrorException error.
Parameters
[in] string $customNumber custom number to validate
Definition at line 218 of file WeirdoCustomDigits.php.
References str_split(), and validateCustomDigit().
Member Data Documentation
WeirdoCustomDigits::$_binChunkPaddingFormat static protected
printf format to left-zero-fill a binary-digit string to the number of bits that corresponds to self::$_hexbinChunkSize
Definition at line 614 of file WeirdoCustomDigits.php.
WeirdoCustomDigits::$_binhexChunkSize static protected
The number of binary digits that corresponds to self::$_hexbinChunkSize.
Definition at line 619 of file WeirdoCustomDigits.php.
WeirdoCustomDigits::$_bitsNeededForRange protected
Array of number of bits by range of numbers.
This is an array that maps a range of numbers to the number of bits required to represent any number in that range. (Actually stored is the limit of the range, log2(n), which starts at zero and ends at one less than the limit.)
Definition at line 602 of file WeirdoCustomDigits.php.
WeirdoCustomDigits::$_digitsArray protected
An array of custom-number digits.
The first element is zero, the second is unity, ...
Definition at line 574 of file WeirdoCustomDigits.php.
WeirdoCustomDigits::$_digitValues protected
An associative array that maps custom-number digits to their numerical values.
Definition at line 579 of file WeirdoCustomDigits.php.
Referenced by WeirdoCustomDigitsGmp\init().
WeirdoCustomDigits::$_fn private
Function vector for mapable class functions.
Definition at line 630 of file WeirdoCustomDigits.php.
WeirdoCustomDigits::$_hexbinChunkSize static protected
The maximum number of hexadecimal digits that both decbin(hexdec($hex)) and dechex(bindec($binary)) can handle.
Definition at line 608 of file WeirdoCustomDigits.php.
WeirdoCustomDigits::$_hexChunkPaddingFormat static protected
printf format to left-zero-fill a hex string to the number of hex digits specified by self::$_hexbinChunkSize
Definition at line 625 of file WeirdoCustomDigits.php.
WeirdoCustomDigits::$_is_using_uc private
Boolean indicator if Unicode is supported by this instance (See initialization parameter $use_uc.)
Definition at line 636 of file WeirdoCustomDigits.php.
WeirdoCustomDigits::$_radix protected
The radix of the custom number.
Definition at line 584 of file WeirdoCustomDigits.php.
Referenced by WeirdoCustomDigitsInt\customFromInternal().
WeirdoCustomDigits::$_rangeNeededForDigits protected
Custom number ranges by number of digits.
This is an array that maps the number of digits in a custom number to the internal representation of the limit for that number as expressed by the number of digits of the custom number. (e.g. 4 digits in base 10 has a limit of 10000.)
Definition at line 593 of file WeirdoCustomDigits.php.
WeirdoCustomDigits::$allowNonCryptoRandom
Set to true only if openssl random is not crypto safe.
Definition at line 71 of file WeirdoCustomDigits.php.
WeirdoCustomDigits::$maximumValue = null static
The maximum value of a number.
If not set or null, there is no practical limit. Otherwise, this is the internally represented maximum number allowed. For the integer subclass WeirdoCustomDigitsInt, for example, this value is PHP_INT_MAX;
Definition at line 83 of file WeirdoCustomDigits.php.
WeirdoCustomDigits::$phpIntegerMaxBits = WeirdoCustomDigits::IEEE_754_SIGNIFICAND_BITS static
Maximum of contiguous range of integers that PHP supports for arithmetic.
Definition at line 74 of file WeirdoCustomDigits.php.
const WeirdoCustomDigits::DIGITS_10_ARABIC_EAST = '٠١٢٣٤٥٦٧٨٩'
Arabic decimal digits (UTF-8)
Definition at line 65 of file WeirdoCustomDigits.php.
const WeirdoCustomDigits::DIGITS_51_READABLE = 'wkW34679AabCcDdEeFfGgHhiJjKLMmNnoPpQqRrsTtUuVvXxYyz'
Digits up to base 51 less likely to be misread These consists of a subset of the typical base-62 digits, less these eleven digits: 0O 1Ll 2Z 5S 8B.
Definition at line 62 of file WeirdoCustomDigits.php.
const WeirdoCustomDigits::DIGITS_62_GMP = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
Digits compatibile with gmp from base 37 to base 62.
Definition at line 56 of file WeirdoCustomDigits.php.
const WeirdoCustomDigits::DIGITS_70 = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_.*~!()-'
Digits for radixes up to base 70 (including bc and gmp up to base 36)
Definition at line 53 of file WeirdoCustomDigits.php.
const WeirdoCustomDigits::IEEE_754_SIGNIFICAND_BITS = 53
Precision of IEEE 754 floating point number.
Definition at line 68 of file WeirdoCustomDigits.php.
const WeirdoCustomDigits::VERSION = '1.0.0'
Class version.
Definition at line 50 of file WeirdoCustomDigits.php.
The documentation for this class was generated from the following file:
WeirdoCustomDigits.php