WeirdoCustomDigits: WeirdoCustomDigitsGmp Class Reference
WeirdoCustomDigitsGmp Class Reference
WeirdoCustomDigits
Implementation of WeirdoCustomDigits using the gmp extension for arithmetic.
Public Member Functions
__construct ($digits=null, $radix=null, $use_uc=true)
For parameters and semantics, see WeirdoCustomDigits::__construct().
customFromDecimal ($decimalNumber, $minCustomDigits=1)
For parameters and semantics, see WeirdoCustomDigits::customFromDecimal().
customFromHex ($hexNumber, $minCustomDigits=1)
For parameters and semantics, see WeirdoCustomDigits::customFromHex().
customFromInternal ($internal, $minCustomDigits=1)
For parameters and semantics, see WeirdoCustomDigits::customFromInternal().
customRandomDigits ($nDigits)
For parameters and semantics, see WeirdoCustomDigits::customRandomDigits().
customRandomFromInternalRange ($rangeInternal)
For parameters and semantics, see WeirdoCustomDigits::customRandomFromInternalRange().
decimalFromCustom ($customNumber)
For parameters and semantics, see WeirdoCustomDigits::decimalFromCustom().
decimalFromInternal ($internal)
For parameters and semantics, see WeirdoCustomDigits::decimalFromInternal().
hexFromCustom ($customNumber)
For parameters and semantics, see WeirdoCustomDigits::hexFromCustom().
hexFromInternal ($internal)
For parameters and semantics, see WeirdoCustomDigits::hexFromInternal().
init ($digits=null, $radix=null, $use_uc=true)
For parameters and semantics, see WeirdoCustomDigits::init().
internalFromCustom ($customNumber, $minCustomDigits=1)
For parameters and semantics, see WeirdoCustomDigits::internalFromCustom().
internalFromDecimal ($decimalNumber)
For parameters and semantics, see WeirdoCustomDigits::internalFromDecimal().
internalFromHex ($hexNumber)
For parameters and semantics, see WeirdoCustomDigits::internalFromHex().
Public Member Functions inherited from WeirdoCustomDigits
__construct ($digits=null, $radix=null, $use_uc=true)
Class constructor.
customFromDecimal ($decimalNumber, $minCustomDigits=1)
Convert a decimal number to a custom-number string.
customFromHex ($hexNumber, $minCustomDigits=1)
Convert a hexadecimal number to a custom-number string.
customFromInternal ($internal, $minCustomDigits=1)
Convert an internally represented number to a custom-number string.
customRandomDigits ($nDigits)
Get a specified number of random custom-number digits.
customRandomFromInternalRange ($rangeInternal)
Get a random custom number within specified range.
decimalFromCustom ($customNumber)
Convert a binary-number string to a decimal-number string.
decimalFromInternal ($internal)
Convert an internally represented number to a decimal-number string.
hexFromCustom ($customNumber)
Convert a custom-number string to a hexadecimal string.
hexFromInternal ($internal)
Convert an internally represented number to a hexadecimal string.
hexFromRandomBits ($nBits)
Get random bits, represented as a hexadecimal string.
init ($digits=null, $radix=null, $use_uc=true)
Class instance initializer.
internalFromCustom ($customNumber)
Convert a custom-number string to an internally represented (opaque) number.
internalFromDecimal ($decimalNumber)
Convert a decimal-number string to an internally represented (opaque) number.
internalFromHex ($hexNumber)
Convert a hexadecimal string to an internally represented (opaque) number.
validateCustomDigit ($customNumberDigit)
Validate a single digit of a custom number.
validateCustomNumber ($customNumber)
Validate a custom-number string.
Static Public Member Functions
static binFromDecimal ($decimalNumber)
For parameters and semantics, see WeirdoCustomDigits::binFromDecimal().
static decimalFromBin ($binNumber)
For parameters and semantics, see WeirdoCustomDigits::decimalFromBin().
static decimalFromHex ($hexNumber)
For parameters and semantics, see WeirdoCustomDigits::decimalFromHex().
static hexFromDecimal ($decimalNumber)
For parameters and semantics, see WeirdoCustomDigits::hexFromDecimal().
Static Public Member Functions inherited from WeirdoCustomDigits
static _initStatic ()
Initialize this class's static properties.
static binFromDecimal ($decimalNumber)
Convert a decimal number/string to a binary-number string of zero (0) and one (1) characters.
static binFromHex ($hexNumber)
Convert a hexadecimal string to a binary-number string of zero (0) and one (1) characters.
static decimalFromBin ($binNumber)
Convert a binary-number string to a decimal-number string.
static decimalFromHex ($hexNumber)
static hexFromBin ($binNumber)
Convert a binary-number string to a hexadecimal string.
static hexFromDecimal ($decimalNumber)
Convert a decimal-number string to a hexadecimal string.
static uc_str_split ($str)
Split a unicode string into an array of its individual characters.
Static Public Attributes
static $maximumValue = null
For parameters and semantics, see WeirdoCustomDigits::$maximumValue.
Static Public Attributes inherited from WeirdoCustomDigits
static $maximumValue = null
The maximum value of a number.
static $phpIntegerMaxBits = WeirdoCustomDigits::IEEE_754_SIGNIFICAND_BITS
Maximum of contiguous range of integers that PHP supports for arithmetic.
Protected Member Functions
_getBitsNeededForRangeInternal ($rangeInternal)
For parameters and semantics, see WeirdoCustomDigits::_getBitsNeededForRangeInternal().
_getRangeNeededForCustomDigits ($nDigits)
For parameters and semantics, see WeirdoCustomDigits::_getRangeNeededForCustomDigits().
Protected Member Functions inherited from WeirdoCustomDigits
_getBitsNeededForRangeInternal ($rangeInternal)
Get the number of binary bits needed to represent a number less than the specified limit.
_getRangeNeededForCustomDigits ($nDigits)
Get the range of numbers needed for the specified number of custom-number digits.
_trim_array_lru (&$array, $maxCount, $chunkSize)
Trim an array, removing least-recently added elements.
str_split ($str)
Split a string into an array of its individual characters, depending on Unicode property.
Additional Inherited Members
Public Attributes inherited from WeirdoCustomDigits
$allowNonCryptoRandom
Set to true only if openssl random is not crypto safe.
const DIGITS_10_ARABIC_EAST = ''
Arabic decimal digits (UTF-8)
const DIGITS_51_READABLE = 'wkW34679AabCcDdEeFfGgHhiJjKLMmNnoPpQqRrsTtUuVvXxYyz'
Digits up to base 51 less likely to be misread These consists of a subset of the typical base-62 digits, less these eleven digits: 0O 1Ll 2Z 5S 8B.
const DIGITS_62_GMP = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
Digits compatibile with gmp from base 37 to base 62.
const DIGITS_70 = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_.*~!()-'
Digits for radixes up to base 70 (including bc and gmp up to base 36)
const IEEE_754_SIGNIFICAND_BITS = 53
Precision of IEEE 754 floating point number.
const VERSION = '1.0.0'
Class version.
Protected Attributes inherited from WeirdoCustomDigits
$_bitsNeededForRange
Array of number of bits by range of numbers.
$_digitsArray
An array of custom-number digits.
$_digitValues
An associative array that maps custom-number digits to their numerical values.
$_radix
The radix of the custom number.
$_rangeNeededForDigits
Custom number ranges by number of digits.
Static Protected Attributes inherited from WeirdoCustomDigits
static $_binChunkPaddingFormat
printf format to left-zero-fill a binary-digit string to the number of bits that corresponds to self::$_hexbinChunkSize
static $_binhexChunkSize
The number of binary digits that corresponds to self::$_hexbinChunkSize.
static $_hexbinChunkSize
The maximum number of hexadecimal digits that both decbin(hexdec($hex)) and dechex(bindec($binary)) can handle.
static $_hexChunkPaddingFormat
printf format to left-zero-fill a hex string to the number of hex digits specified by self::$_hexbinChunkSize
Detailed Description
Implementation of WeirdoCustomDigits using the gmp extension for arithmetic.
Requirements
gmp extension (See http://php.net/gmp)
Limitations
None more than WeirdoCustomDigits.
The "internally represented" format for values of this subclass is the internal value that gmp uses, e.g. the value returned by gmp_init().
Definition at line 35 of file WeirdoCustomDigitsGmp.php.
Constructor & Destructor Documentation
WeirdoCustomDigitsGmp::__construct ($digits = null, $radix = null, $use_uc = true)
For parameters and semantics, see WeirdoCustomDigits::__construct().
Definition at line 45 of file WeirdoCustomDigitsGmp.php.
Member Function Documentation
WeirdoCustomDigitsGmp::_getBitsNeededForRangeInternal ($rangeInternal) protected
For parameters and semantics, see WeirdoCustomDigits::_getBitsNeededForRangeInternal().
Definition at line 203 of file WeirdoCustomDigitsGmp.php.
Referenced by customRandomFromInternalRange().
WeirdoCustomDigitsGmp::_getRangeNeededForCustomDigits ($nDigits) protected
For parameters and semantics, see WeirdoCustomDigits::_getRangeNeededForCustomDigits().
Definition at line 194 of file WeirdoCustomDigitsGmp.php.
Referenced by customRandomDigits().
static WeirdoCustomDigitsGmp::binFromDecimal ($decimalNumber) static
For parameters and semantics, see WeirdoCustomDigits::binFromDecimal().
Definition at line 69 of file WeirdoCustomDigitsGmp.php.
WeirdoCustomDigitsGmp::customFromDecimal ($decimalNumber, $minCustomDigits = 1)
For parameters and semantics, see WeirdoCustomDigits::customFromDecimal().
Definition at line 74 of file WeirdoCustomDigitsGmp.php.
References customFromInternal().
WeirdoCustomDigitsGmp::customFromHex ($hexNumber, $minCustomDigits = 1)
For parameters and semantics, see WeirdoCustomDigits::customFromHex().
Definition at line 80 of file WeirdoCustomDigitsGmp.php.
References customFromInternal().
WeirdoCustomDigitsGmp::customFromInternal ($internal, $minCustomDigits = 1)
For parameters and semantics, see WeirdoCustomDigits::customFromInternal().
Definition at line 86 of file WeirdoCustomDigitsGmp.php.
Referenced by customFromDecimal(), customFromHex(), and customRandomFromInternalRange().
WeirdoCustomDigitsGmp::customRandomDigits ($nDigits)
For parameters and semantics, see WeirdoCustomDigits::customRandomDigits().
Definition at line 103 of file WeirdoCustomDigitsGmp.php.
References _getRangeNeededForCustomDigits(), and customRandomFromInternalRange().
WeirdoCustomDigitsGmp::customRandomFromInternalRange ($rangeInternal)
For parameters and semantics, see WeirdoCustomDigits::customRandomFromInternalRange().
Definition at line 111 of file WeirdoCustomDigitsGmp.php.
References _getBitsNeededForRangeInternal(), customFromInternal(), and WeirdoCustomDigits\hexFromRandomBits().
Referenced by customRandomDigits().
static WeirdoCustomDigitsGmp::decimalFromBin ($binNumber) static
For parameters and semantics, see WeirdoCustomDigits::decimalFromBin().
Definition at line 135 of file WeirdoCustomDigitsGmp.php.
WeirdoCustomDigitsGmp::decimalFromCustom ($customNumber)
For parameters and semantics, see WeirdoCustomDigits::decimalFromCustom().
Definition at line 145 of file WeirdoCustomDigitsGmp.php.
References internalFromCustom().
static WeirdoCustomDigitsGmp::decimalFromHex ($hexNumber) static
For parameters and semantics, see WeirdoCustomDigits::decimalFromHex().
Definition at line 140 of file WeirdoCustomDigitsGmp.php.
WeirdoCustomDigitsGmp::decimalFromInternal ($internal)
For parameters and semantics, see WeirdoCustomDigits::decimalFromInternal().
Definition at line 150 of file WeirdoCustomDigitsGmp.php.
WeirdoCustomDigitsGmp::hexFromCustom ($customNumber)
For parameters and semantics, see WeirdoCustomDigits::hexFromCustom().
Definition at line 160 of file WeirdoCustomDigitsGmp.php.
References internalFromCustom().
static WeirdoCustomDigitsGmp::hexFromDecimal ($decimalNumber) static
For parameters and semantics, see WeirdoCustomDigits::hexFromDecimal().
Definition at line 155 of file WeirdoCustomDigitsGmp.php.
WeirdoCustomDigitsGmp::hexFromInternal ($internal)
For parameters and semantics, see WeirdoCustomDigits::hexFromInternal().
Definition at line 165 of file WeirdoCustomDigitsGmp.php.
WeirdoCustomDigitsGmp::init ($digits = null, $radix = null, $use_uc = true)
For parameters and semantics, see WeirdoCustomDigits::init().
Definition at line 56 of file WeirdoCustomDigitsGmp.php.
References WeirdoCustomDigits\$_digitValues.
WeirdoCustomDigitsGmp::internalFromCustom ($customNumber, $minCustomDigits = 1)
For parameters and semantics, see WeirdoCustomDigits::internalFromCustom().
Definition at line 170 of file WeirdoCustomDigitsGmp.php.
References WeirdoCustomDigits\str_split().
Referenced by decimalFromCustom(), and hexFromCustom().
WeirdoCustomDigitsGmp::internalFromDecimal ($decimalNumber)
For parameters and semantics, see WeirdoCustomDigits::internalFromDecimal().
Definition at line 184 of file WeirdoCustomDigitsGmp.php.
WeirdoCustomDigitsGmp::internalFromHex ($hexNumber)
For parameters and semantics, see WeirdoCustomDigits::internalFromHex().
Definition at line 189 of file WeirdoCustomDigitsGmp.php.
Member Data Documentation
WeirdoCustomDigitsGmp::$maximumValue = null static
For parameters and semantics, see WeirdoCustomDigits::$maximumValue.
For this class, the value is null, meaning that there is no limit.
Definition at line 42 of file WeirdoCustomDigitsGmp.php.
The documentation for this class was generated from the following file:
WeirdoCustomDigitsGmp.php