WeirdoCustomDigits: WeirdoCustomDigitsInt Class Reference
WeirdoCustomDigitsInt Class Reference
WeirdoCustomDigits
Implementation of WeirdoCustomDigits using built-in integer arithmetic.
Public Member Functions
customFromDecimal ($decimalNumber, $minCustomDigits=1)
For parameters and semantics, see WeirdoCustomDigits::customFromDecimal().
customFromHex ($hexNumber, $minCustomDigits=1)
For parameters and semantics, see WeirdoCustomDigits::customFromHex().
customFromInternal ($internal, $minCustomDigits=1)
For parameters and semantics, see WeirdoCustomDigits::customFromInternal().
customRandomDigits ($nDigits, $allowOverflow=false)
For parameters and semantics, see WeirdoCustomDigits::customRandomDigits().
customRandomFromInternalRange ($rangeInternal)
For parameters and semantics, see WeirdoCustomDigits::customRandomFromInternalRange().
decimalFromCustom ($customNumber)
For parameters and semantics, see WeirdoCustomDigits::decimalFromCustom().
decimalFromInternal ($internal)
For parameters and semantics, see WeirdoCustomDigits::decimalFromInternal().
hexFromCustom ($customNumber)
For parameters and semantics, see WeirdoCustomDigits::hexFromCustom().
hexFromInternal ($internal)
For parameters and semantics, see WeirdoCustomDigits::hexFromInternal().
init ($digits=null, $radix=null, $use_uc=true)
For parameters and semantics, see WeirdoCustomDigits::init().
internalFromCustom ($customNumber)
For parameters and semantics, see WeirdoCustomDigits::internalFromCustom().
internalFromDecimal ($decimalNumber)
For parameters and semantics, see WeirdoCustomDigits::internalFromDecimal().
internalFromHex ($hexNumber)
For parameters and semantics, see WeirdoCustomDigits::internalFromHex().
Public Member Functions inherited from WeirdoCustomDigits
__construct ($digits=null, $radix=null, $use_uc=true)
Class constructor.
customFromDecimal ($decimalNumber, $minCustomDigits=1)
Convert a decimal number to a custom-number string.
customFromHex ($hexNumber, $minCustomDigits=1)
Convert a hexadecimal number to a custom-number string.
customFromInternal ($internal, $minCustomDigits=1)
Convert an internally represented number to a custom-number string.
customFromRaw ($rawString, $minCustomDigits=1)
Convert an internally represented number to a raw byte string.
customRandomDigits ($nDigits, $allowOverflow=false)
Get a specified number of random custom-number digits.
customRandomFromInternalRange ($rangeInternal)
Get a random custom number within specified range.
decimalFromCustom ($customNumber)
Convert a binary-number string to a decimal-number string.
decimalFromInternal ($internal)
Convert an internally represented number to a decimal-number string.
hexFromCustom ($customNumber)
Convert a custom-number string to a hexadecimal string.
hexFromInternal ($internal)
Convert an internally represented number to a hexadecimal string.
hexFromRandomBits ($nBits)
Get random bits, represented as a hexadecimal string.
init ($digits=null, $radix=null, $use_uc=true)
Class instance initializer.
internalFromCustom ($customNumber)
Convert a custom-number string to an internally represented (opaque) number.
internalFromDecimal ($decimalNumber)
Convert a decimal-number string to an internally represented (opaque) number.
internalFromHex ($hexNumber)
Convert a hexadecimal string to an internally represented (opaque) number.
rawFromCustom ($customNumber)
Convert a custom-number string to a raw byte string.
validateCustomDigit ($customNumberDigit)
Validate a single digit of a custom number.
validateCustomNumber ($customNumber)
Validate a custom-number string.
Static Public Member Functions
static _initStatic ()
For semantics, see WeirdoCustomDigits::_initStatic().
static binFromDecimal ($decimalNumber)
For parameters and semantics, see WeirdoCustomDigits::binFromDecimal().
static decimalFromBin ($binNumber)
For parameters and semantics, see WeirdoCustomDigits::decimalFromBin().
static decimalFromHex ($hexNumber)
For parameters and semantics, see WeirdoCustomDigits::decimalFromHex().
static hexFromDecimal ($decimalNumber)
For parameters and semantics, see WeirdoCustomDigits::hexFromDecimal().
Static Public Member Functions inherited from WeirdoCustomDigits
static _initStatic ()
Initialize this class's static properties.
static binFromDecimal ($decimalNumber)
Convert a decimal number/string to a binary-number string of zero (0) and one (1) characters.
static binFromHex ($hexNumber)
Convert a hexadecimal string to a binary-number string of zero (0) and one (1) characters.
static decimalFromBin ($binNumber)
Convert a binary-number string to a decimal-number string.
static decimalFromHex ($hexNumber)
static hexFromBin ($binNumber)
Convert a binary-number string to a hexadecimal string.
static hexFromDecimal ($decimalNumber)
Convert a decimal-number string to a hexadecimal string.
static hexFromRaw ($rawString)
Convert a raw byte string to a hexadecimal string.
static rawFromHex ($hexNumber)
Convert a hexadecimal string to a raw byte string.
static uc_str_split ($str)
Split a unicode string into an array of its individual characters.
Static Public Attributes
static $maximumValue
The maximum value of a number.
Static Public Attributes inherited from WeirdoCustomDigits
static $maximumValue = null
The maximum value of a number.
static $phpIntegerMaxBits = WeirdoCustomDigits::IEEE_754_SIGNIFICAND_BITS
Maximum of contiguous range of integers that PHP supports for arithmetic.
Protected Member Functions
_getBitsNeededForRangeInternal ($rangeInternal)
For parameters and semantics, see WeirdoCustomDigits::_getBitsNeededForRangeInternal().
_getRangeNeededForCustomDigits ($nDigitsDecimal)
For parameters and semantics, see WeirdoCustomDigits::_getRangeNeededForCustomDigits().
Protected Member Functions inherited from WeirdoCustomDigits
_getBitsNeededForRangeInternal ($rangeInternal)
Get the number of binary bits needed to represent a number less than the specified limit.
_getRangeNeededForCustomDigits ($nDigits)
Get the range of numbers needed for the specified number of custom-number digits.
_trim_array_lru (&$array, $maxCount, $chunkSize)
Trim an array, removing least-recently added elements.
str_split ($str)
Split a string into an array of its individual characters, depending on Unicode property.
Private Attributes
$_maxCustomRandomDigits
The maximum number of random custom number digits we can generate at once.
Additional Inherited Members
Public Attributes inherited from WeirdoCustomDigits
$allowNonCryptoRandom
Set to true only if openssl random is not crypto safe.
const DIGITS_10_ARABIC_EAST = ''
Arabic decimal digits (UTF-8)
const DIGITS_51_READABLE = 'wkW34679AabCcDdEeFfGgHhiJjKLMmNnoPpQqRrsTtUuVvXxYyz'
Digits up to base 51 less likely to be misread These consists of a subset of the typical base-62 digits, less these eleven digits: 0O 1Ll 2Z 5S 8B.
const DIGITS_62_GMP = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
Digits compatibile with gmp from base 37 to base 62.
const DIGITS_70 = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_.*~!()-'
Digits for radixes up to base 70 (compatible with base_convert and gmp up to base 36)
const DIGITS_BASE64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
Digits compatible with base64 encoding.
const IEEE_754_SIGNIFICAND_BITS = 53
Precision of IEEE 754 floating point number.
const VERSION = '1.0.1'
Class version.
Protected Attributes inherited from WeirdoCustomDigits
$_bitsNeededForRange
Array of number of bits by range of numbers.
$_digitsArray
An array of custom-number digits.
$_digitValues
An associative array that maps custom-number digits to their numerical values.
$_radix
The radix of the custom number.
$_rangeNeededForDigits
Custom number ranges by number of digits.
Static Protected Attributes inherited from WeirdoCustomDigits
static $_binChunkPaddingFormat
printf format to left-zero-fill a binary-digit string to the number of bits that corresponds to self::$_hexbinChunkSize
static $_binhexChunkSize
The number of binary digits that corresponds to self::$_hexbinChunkSize.
static $_hexbinChunkSize
The maximum number of hexadecimal digits that both decbin(hexdec($hex)) and dechex(bindec($binary)) can handle.
static $_hexChunkPaddingFormat
printf format to left-zero-fill a hex string to the number of hex digits specified by self::$_hexbinChunkSize
Detailed Description
Implementation of WeirdoCustomDigits using built-in integer arithmetic.
Requirements
None more than WeirdoCustomDigits.
Limitations
range limited by the smaller of PHP_INT_MAX and the maximum integer supported by floating point arithmetic.
The "internally represented" format for values of this subclass is a PHP int.
Definition at line 42 of file WeirdoCustomDigitsInt.php.
Member Function Documentation
WeirdoCustomDigitsInt::_getBitsNeededForRangeInternal ($rangeInternal) protected
For parameters and semantics, see WeirdoCustomDigits::_getBitsNeededForRangeInternal().
Access:
private
Definition at line 201 of file WeirdoCustomDigitsInt.php.
Referenced by customRandomFromInternalRange().
WeirdoCustomDigitsInt::_getRangeNeededForCustomDigits ($nDigitsDecimal) protected
For parameters and semantics, see WeirdoCustomDigits::_getRangeNeededForCustomDigits().
Access:
private
Definition at line 215 of file WeirdoCustomDigitsInt.php.
Referenced by customRandomDigits().
static WeirdoCustomDigitsInt::_initStatic () static
For semantics, see WeirdoCustomDigits::_initStatic().
Access:
private
Definition at line 230 of file WeirdoCustomDigitsInt.php.
static WeirdoCustomDigitsInt::binFromDecimal ($decimalNumber) static
For parameters and semantics, see WeirdoCustomDigits::binFromDecimal().
Definition at line 58 of file WeirdoCustomDigitsInt.php.
WeirdoCustomDigitsInt::customFromDecimal ($decimalNumber, $minCustomDigits = 1)
For parameters and semantics, see WeirdoCustomDigits::customFromDecimal().
Definition at line 63 of file WeirdoCustomDigitsInt.php.
References customFromInternal().
WeirdoCustomDigitsInt::customFromHex ($hexNumber, $minCustomDigits = 1)
For parameters and semantics, see WeirdoCustomDigits::customFromHex().
Definition at line 68 of file WeirdoCustomDigitsInt.php.
References customFromInternal().
Referenced by customRandomFromInternalRange().
WeirdoCustomDigitsInt::customFromInternal ($internal, $minCustomDigits = 1)
For parameters and semantics, see WeirdoCustomDigits::customFromInternal().
Definition at line 73 of file WeirdoCustomDigitsInt.php.
References WeirdoCustomDigits\$_radix.
Referenced by customFromDecimal(), and customFromHex().
WeirdoCustomDigitsInt::customRandomDigits ($nDigits, $allowOverflow = false)
For parameters and semantics, see WeirdoCustomDigits::customRandomDigits().
Definition at line 146 of file WeirdoCustomDigitsInt.php.
References $_maxCustomRandomDigits, _getRangeNeededForCustomDigits(), and customRandomFromInternalRange().
WeirdoCustomDigitsInt::customRandomFromInternalRange ($rangeInternal)
For parameters and semantics, see WeirdoCustomDigits::customRandomFromInternalRange().
Definition at line 184 of file WeirdoCustomDigitsInt.php.
References _getBitsNeededForRangeInternal(), customFromHex(), and WeirdoCustomDigits\hexFromRandomBits().
Referenced by customRandomDigits().
static WeirdoCustomDigitsInt::decimalFromBin ($binNumber) static
For parameters and semantics, see WeirdoCustomDigits::decimalFromBin().
Definition at line 92 of file WeirdoCustomDigitsInt.php.
WeirdoCustomDigitsInt::decimalFromCustom ($customNumber)
For parameters and semantics, see WeirdoCustomDigits::decimalFromCustom().
Definition at line 97 of file WeirdoCustomDigitsInt.php.
References internalFromCustom().
static WeirdoCustomDigitsInt::decimalFromHex ($hexNumber) static
For parameters and semantics, see WeirdoCustomDigits::decimalFromHex().
Definition at line 87 of file WeirdoCustomDigitsInt.php.
WeirdoCustomDigitsInt::decimalFromInternal ($internal)
For parameters and semantics, see WeirdoCustomDigits::decimalFromInternal().
Definition at line 102 of file WeirdoCustomDigitsInt.php.
WeirdoCustomDigitsInt::hexFromCustom ($customNumber)
For parameters and semantics, see WeirdoCustomDigits::hexFromCustom().
Definition at line 112 of file WeirdoCustomDigitsInt.php.
References internalFromCustom().
static WeirdoCustomDigitsInt::hexFromDecimal ($decimalNumber) static
For parameters and semantics, see WeirdoCustomDigits::hexFromDecimal().
Definition at line 107 of file WeirdoCustomDigitsInt.php.
WeirdoCustomDigitsInt::hexFromInternal ($internal)
For parameters and semantics, see WeirdoCustomDigits::hexFromInternal().
Definition at line 117 of file WeirdoCustomDigitsInt.php.
WeirdoCustomDigitsInt::init ($digits = null, $radix = null, $use_uc = true)
For parameters and semantics, see WeirdoCustomDigits::init().
Definition at line 52 of file WeirdoCustomDigitsInt.php.
WeirdoCustomDigitsInt::internalFromCustom ($customNumber)
For parameters and semantics, see WeirdoCustomDigits::internalFromCustom().
Definition at line 122 of file WeirdoCustomDigitsInt.php.
References WeirdoCustomDigits\str_split().
Referenced by decimalFromCustom(), and hexFromCustom().
WeirdoCustomDigitsInt::internalFromDecimal ($decimalNumber)
For parameters and semantics, see WeirdoCustomDigits::internalFromDecimal().
Definition at line 136 of file WeirdoCustomDigitsInt.php.
WeirdoCustomDigitsInt::internalFromHex ($hexNumber)
For parameters and semantics, see WeirdoCustomDigits::internalFromHex().
Definition at line 141 of file WeirdoCustomDigitsInt.php.
Member Data Documentation
WeirdoCustomDigitsInt::$_maxCustomRandomDigits private
The maximum number of random custom number digits we can generate at once.
Definition at line 239 of file WeirdoCustomDigitsInt.php.
Referenced by customRandomDigits().
WeirdoCustomDigitsInt::$maximumValue static
The maximum value of a number.
For this class, the value is the lesser of PHP_INT_MAX and pow(2, self::$phpIntegerMaxBits)-1
Definition at line 49 of file WeirdoCustomDigitsInt.php.
The documentation for this class was generated from the following file:
WeirdoCustomDigitsInt.php